spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=production_db;encrypt=false;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=production123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

server.port=8080

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
spring.jpa.open-in-view=true