version: '3.8'

services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "production123"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - production-network

  backend:
    build: ./backend-production
    container_name: backend
    ports:
      - "8080:8080"
    depends_on:
      - sqlserver
    environment:
      SPRING_DATASOURCE_URL: jdbc:sqlserver://sqlserver:1433;databaseName=production_db;encrypt=false;trustServerCertificate=true
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: production123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_AUTOCONFIGURE_EXCLUDE: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
    networks:
      - production-network

  frontend:
    build: ./frontend-production
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - production-network

networks:
  production-network:
    driver: bridge

volumes:
  sqlserver_data: